apiVersion: apps/v1
kind: Deployment
metadata:
  name: eswj-cms
  namespace: eswj
  labels:
    app: eswj-cms
spec:
  selector:
    matchLabels:
      app: eswj-cms
  template:
    metadata:
      labels:
        app: eswj-cms
    spec:
      containers:
        - name: ghost
          image: ghost
          imagePullPolicy: Always
          ports:
            - containerPort: 2368
              name: cms-port
          envFrom:
            - configMapRef:
                name: eswj-config
          env:
            - name: url
              value: https://blog.everysecondwithjesus.org
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: eswj-secret
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: eswj-secret
            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: eswj-secret
            - name: mail__from
              valueFrom:
                secretKeyRef:
                  key: mail_from
                  name: eswj-secret
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  key: mail_pass
                  name: eswj-secret
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  key: mail_user
                  name: eswj-secret

---
apiVersion: v1
kind: Service
metadata:
  namespace: eswj
  name: eswj-cms
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: cms-port
  selector:
    app: eswj-cms





